### ISSUE TITLE
1.0.1 ?

### ISSUE THREAD

**Issue by benoitc** [erlangpack/mimetypes#24]
Would be cool if you could tag a new release with the latest minors changes  including the new license header. It would clarify the legal stuff there.

**Comment by lemenkov** [comment]
Ping! :)
Any news on this?

**Comment by ddeboer** [comment]
Additionally, publishing this module to Hex would be great!

@yrashk Are you still maintaining this library? If not, we could move it to https://github.com/erlangpack where the ErlangPack team will take care of releasing and publishing it to Hex. Please let me know if you’re okay with that! Of course, you’ll keep full commit rights and get credits.

**Comment by yrashk** [comment]
@ddeboer I am not. Happy to move it over.

**Comment by yrashk** [comment]
However, unfortunately, I don't have admin rights in this org anymore. So it would have to be another repo.

**Comment by ddeboer** [comment]
@yrashk Thanks for the swift reply!

It would be best to _move_ the repository (to the ErlangPack organization). That way, everyone will be redirected to the new location. 

@kevinsalter @mtwilliams Do you have admin rights to this repository? If so, could you please move it to the ErlangPack organization (and let me know who I should grant full commit rights to)?

**Comment by mtwilliams** [comment]
I've added @yrashk as an administrator.

**Comment by yrashk** [comment]
I tried to transfer the repository, but GitHub says I don't have a right to create reois at erlangpack. 
![screenshot_20170714-071251](https://user-images.githubusercontent.com/452/28193003-0b06cfdc-6864-11e7-9f27-3668bcd60d6a.png)

**Comment by ddeboer** [comment]
I invited you to the ErlangPack organization, which should grant you the required rights.

**Comment by yrashk** [comment]
Done!

**Comment by ddeboer** [comment]
Thanks, @yrashk!
